---
- name: Configure systemd journal upload tls and url settings
  become: true
  ansible.builtin.template:
    src: 'templates/journal-upload.conf.j2'
    backup: true
    dest: '/etc/systemd/journal-upload.conf'
    owner: 'root'
    group: 'root'
    mode: '0644'
  notify: 'systemctl restart systemd-journal-upload.service'

#- name: Create systemd service for rsyslog server
#  become: true
#  ansible.builtin.template:
#    src: 'templates/systemd-journal-remote.service.j2'
#    backup: true
#    dest: "/lib/systemd/system/{{ item.systemd_file }}"
#    owner: 'root'
#    group: 'root'
#    mode: '0644'
#  with_items: "{{ journald_server__systemd_jobs }}"
#  notify: 'systemctl restart remotesyslogserver'

- name: Reload systemd daemon
  become: true
  ansible.builtin.systemd_service:
    daemon_reload: true
  notify: 'systemctl restart systemd-journal-upload.service'
